from __future__ import annotations

from copy import deepcopy
import json
from pathlib import Path
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from board_catalog import (  # noqa: E402
    BoardCatalogError, default_board, load_catalog, selector_source,
    validate_descriptor,
)


class BoardCatalogTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.catalog = load_catalog()

    def test_repository_catalog_contains_qualified_and_bringup_boards(self):
        self.assertEqual(
            self.catalog["lilygo_t_display_s3_pro"]["support_status"],
            "qualified")
        self.assertEqual(
            self.catalog["elecrow_dle06235b"]["support_status"], "bringup")

    def test_selector_is_generated_from_descriptor(self):
        source = selector_source(self.catalog["lilygo_t_display_s3_pro"])
        self.assertEqual(
            source,
            "# Generated by the authenticated TartLab adult provisioning tool.\n"
            "from t_display_s3_pro_modern import *\n")

    def test_bringup_board_cannot_claim_qualification(self):
        descriptor = deepcopy(self.catalog["elecrow_dle06235b"])
        descriptor["qualification"] = {
            "release_version": "modern-v0",
            "evidence": "boards/elecrow_dle06235b/BRINGUP_RESULTS.md",
        }
        with self.assertRaisesRegex(
                BoardCatalogError, "bringup boards cannot claim qualification"):
            validate_descriptor(descriptor)

    def test_candidate_requires_selector_and_firmware(self):
        descriptor = deepcopy(self.catalog["elecrow_dle06235b"])
        descriptor["support_status"] = "candidate"
        with self.assertRaisesRegex(BoardCatalogError, "require a selector"):
            validate_descriptor(descriptor)

    def test_runtime_profile_selects_an_explicit_qualified_default(self):
        self.assertEqual(
            default_board("lvgl-modern")["id"],
            "lilygo_t_display_s3_pro")

    def test_directory_name_must_match_id(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            boards = root / "boards" / "wrong_name"
            boards.mkdir(parents=True)
            descriptor = deepcopy(self.catalog["elecrow_dle06235b"])
            for source in descriptor["documentation"]:
                target = root / source
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text("test", encoding="utf-8")
            (boards / "board.json").write_text(
                json.dumps(descriptor), encoding="utf-8")
            with self.assertRaisesRegex(
                    BoardCatalogError, "directory name"):
                load_catalog(root=root)


if __name__ == "__main__":
    unittest.main()
