"""Safely provision or migrate a TartLab device to the managed-modern profile.

The default CLI action is a read-only release inspection.  Device mutation
requires --execute, --confirm-erase, an authenticated source tag, and a durable
workspace outside the repository.  The workspace may contain Wi-Fi settings
and student files; it must be treated as sensitive and retained until the
device has completed a healthy boot.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tarfile
import time
from typing import Any, Sequence


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from check_modern_release import check as check_modern_release  # noqa: E402
from check_modern_support_window import validate_backup as validate_support_window  # noqa: E402
from phase1_device import RawRepl, inventory as device_inventory  # noqa: E402
from release_utils import (  # noqa: E402
    file_inventory, inventory_identifier, sha256_file, write_json,
)


PROFILE = "lvgl-modern"
FIRMWARE_SHA256 = (
    "187a04dc9c74be161aa46d8b8f76ff64cb7eb4305b15c6d416e5fef471c7f2ab")
LEGACY_FIRMWARE = (
    ROOT / "firmware/legacy-mp123/"
    "ESP32_GENERIC_S3-SPIRAM_OCT-20240602-v1.23.0.bin")
LEGACY_FIRMWARE_SHA256 = (
    "41a750a8f047224e3e0a7544a626338c252407df420e2b94dcb0d2dad9793212")
LEGACY_IDENTITY_REGIONS = [
    {
        "name": "bootloader-and-partition-table",
        "offset": 0,
        "size": 36864,
        "sha256": "6b22cf113eaffda9ac43e236f873c62dccceed233f1d0f5114b5e8b3de1ca414",
    },
    {
        "name": "factory-application",
        "offset": 65536,
        "size": 1565888,
        "sha256": "9d6998170b5bf7e8568be2aa2845e25fe98bd622f945e1fdd9740a35b12ffa8d",
    },
]
MODERN_REPOSITORY = "tdhoward/TartLab-modern-releases"
MODERN_SELECTOR = (
    "# Generated by the authenticated TartLab adult provisioning tool.\n"
    "from t_display_s3_pro_modern import *\n")
BACKUP_PATHS = (
    "/device", "/state", "/files/user", "/hdwconfig.py", "/settings.json",
    "/repos.json", "/logs", "/app.py",
)
STAGES = (
    "verified", "backup_captured", "backed_up", "awaiting_health", "complete")


def _read_object(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("%s: expected a JSON object" % path)
    return value


def _replace_directory(path: Path, parent: Path) -> None:
    path = path.resolve()
    parent = parent.resolve()
    if path.parent != parent or path == parent:
        raise ValueError("refusing to replace a directory outside the workspace")
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True)


def _workspace_path(workspace: Path) -> Path:
    workspace = workspace.resolve()
    if workspace == ROOT or ROOT in workspace.parents:
        raise ValueError(
            "Provisioning workspace must be outside the repository because it "
            "may contain credentials and student files")
    if workspace == Path(workspace.anchor):
        raise ValueError("Provisioning workspace cannot be a filesystem root")
    return workspace


def _stage_index(stage: str) -> int:
    try:
        return STAGES.index(stage)
    except ValueError as exc:
        raise ValueError("unknown provisioning journal stage: %s" % stage) from exc


def _write_journal(path: Path, journal: dict[str, Any]) -> None:
    temporary = path.with_suffix(".json.tmp")
    write_json(temporary, journal)
    os.replace(temporary, path)


def _safe_member_path(image: Path, target: str, member_name: str) -> Path:
    member_name = member_name.replace("\\", "/")
    parts = member_name.split("/")
    if member_name.startswith("/") or any(part in ("", ".", "..") for part in parts):
        raise ValueError("unsafe modern archive member: %s" % member_name)
    target_parts = [part for part in target.replace("\\", "/").split("/") if part]
    destination = image.joinpath(*target_parts, *parts).resolve()
    if image.resolve() not in destination.parents:
        raise ValueError("modern archive member escapes the provisioning image")
    return destination


def _extract_release_image(release: Path, image: Path,
                           manifest: dict[str, Any]) -> None:
    for package in manifest["packages"]:
        archive_path = release / package["file_name"]
        with tarfile.open(archive_path, "r") as archive:
            for member in archive.getmembers():
                if not member.isfile():
                    continue
                destination = _safe_member_path(
                    image, package["target"], member.name)
                destination.parent.mkdir(parents=True, exist_ok=True)
                stream = archive.extractfile(member)
                if stream is None:
                    raise ValueError("modern archive member cannot be read")
                with destination.open("wb") as output:
                    shutil.copyfileobj(stream, output)


def _copy_if_present(source: Path, destination: Path) -> bool:
    if source.is_file():
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        return True
    return False


def _copy_tree_if_present(source: Path, destination: Path) -> bool:
    if not source.is_dir():
        return False
    destination.mkdir(parents=True, exist_ok=True)
    shutil.copytree(source, destination, dirs_exist_ok=True)
    return True


def _selected_app(backup: Path) -> str:
    canonical = backup / "state/selected_app.json"
    if canonical.is_file():
        value = _read_object(canonical).get("filename")
        if isinstance(value, str) and re.fullmatch(
                r"[A-Za-z0-9_]+(?:/[A-Za-z0-9_]+)*\.py", value):
            return value
        raise ValueError("backup contains an unsafe selected application")
    legacy = backup / "app.py"
    if legacy.is_file():
        lines = legacy.read_text(encoding="utf-8").splitlines()
        if len(lines) >= 2 and lines[1].startswith("# "):
            value = lines[1][2:].strip()
            if re.fullmatch(r"[A-Za-z0-9_]+(?:/[A-Za-z0-9_]+)*\.py", value):
                return value
    return "hello.py"


def _validate_migration_source(backup: Path) -> dict[str, str]:
    return validate_support_window(backup)


def _migrated_repos(backup: Path, version: str) -> tuple[dict[str, Any], str]:
    source = backup / "state/repos.json"
    if not source.is_file():
        source = backup / "repos.json"
    if source.is_file():
        repos = _read_object(source)
    else:
        repos = {"dbver": 1, "list": []}
    entries = repos.get("list")
    if not isinstance(entries, list):
        raise ValueError("backup release state has no repository list")
    tartlab = None
    for item in entries:
        if isinstance(item, dict) and item.get("name") == "TartLab":
            tartlab = item
            break
    if tartlab is None:
        tartlab = {"name": "TartLab", "installed_version": "unprovisioned"}
        entries.append(tartlab)
    previous = tartlab.get("installed_version")
    if not isinstance(previous, str) or not previous:
        previous = "unprovisioned"
    tartlab.update({
        "repo": MODERN_REPOSITORY,
        "installed_version": previous,
        "runtime_profile": PROFILE,
        "manifest": "modern-manifest.json",
        "firmware_sha256": FIRMWARE_SHA256,
    })
    repos["list"] = entries
    return repos, previous


def prepare_image(release: Path, backup: Path, image: Path, *,
                  version: str, mode: str, backup_identifier: str) -> None:
    """Reconstruct a complete device filesystem without mutating a device."""

    _replace_directory(image, image.parent)
    manifest = _read_object(release / "modern-manifest.json")
    _extract_release_image(release, image, manifest)
    for required in ("boot.py", "main.py", "recovery/recovery.py"):
        if not (image / required).is_file():
            raise ValueError("modern provisioning image is missing %s" % required)

    device = image / "device"
    if mode == "migrate":
        _validate_migration_source(backup)
        _copy_tree_if_present(backup / "device", device)
    device.mkdir(parents=True, exist_ok=True)
    (device / "hdwconfig.py").write_text(
        MODERN_SELECTOR, encoding="utf-8", newline="\n")

    state = image / "state"
    state.mkdir(parents=True, exist_ok=True)
    if mode == "migrate":
        # Preserve the legacy root files verbatim for rollback/audit.  The
        # modern runtime resolves /device before /, so the translated selector
        # remains authoritative without discarding protected source data.
        _copy_if_present(backup / "app.py", image / "app.py")
        _copy_if_present(backup / "hdwconfig.py", image / "hdwconfig.py")
        _copy_if_present(
            backup / "state/settings.json", state / "settings.json") or \
            _copy_if_present(backup / "settings.json", state / "settings.json")
        _copy_tree_if_present(backup / "state/logs", state / "logs") or \
            _copy_tree_if_present(backup / "logs", state / "logs")
        _copy_tree_if_present(backup / "files/user", image / "files/user")
    repos, previous = _migrated_repos(backup, version)
    write_json(state / "repos.json", repos)
    write_json(state / "selected_app.json", {
        "schema": 1,
        "filename": _selected_app(backup) if mode == "migrate" else "hello.py",
    })
    write_json(state / "update.json", {
        "schema": 1,
        "status": "pending_health",
        "source": "adult-provisioning",
        "source_profile": "legacy-mp123" if mode == "migrate" else "clean",
        "backup_identifier": backup_identifier,
        "repos": [{
            "name": "TartLab",
            "previous_version": previous,
            "pending_version": version,
        }],
    })


def _release_identity(release: Path) -> tuple[dict[str, Any], str]:
    manifest = _read_object(release / "modern-manifest.json")
    check_modern_release(release, PROFILE, FIRMWARE_SHA256)
    return manifest, sha256_file(release / "checksums.json")


def provision(release: Path, workspace: Path, mode: str, transport: Any, *,
              resume: bool = False) -> dict[str, Any]:
    """Run or resume the host transaction using an injected device transport."""

    if mode not in ("clean", "migrate"):
        raise ValueError("provisioning mode must be clean or migrate")
    release = release.resolve()
    manifest, release_identifier = _release_identity(release)
    version = manifest["version"]
    firmware_record = manifest["published_assets"]["firmware"]
    firmware = release / firmware_record["file_name"]
    workspace = _workspace_path(workspace)
    journal_path = workspace / "provisioning-journal.json"

    if journal_path.is_file():
        if not resume:
            raise ValueError("provisioning journal exists; use --resume")
        journal = _read_object(journal_path)
        expected = {
            "mode": mode,
            "release_checksums_sha256": release_identifier,
            "version": version,
            "profile": PROFILE,
        }
        if any(journal.get(key) != value for key, value in expected.items()):
            raise ValueError("provisioning journal does not match this operation")
    else:
        if resume:
            raise ValueError("no provisioning journal exists to resume")
        if workspace.exists() and any(workspace.iterdir()):
            raise ValueError("new provisioning workspace must be empty")
        workspace.mkdir(parents=True, exist_ok=True)
        journal = {
            "schema": 1,
            "stage": "verified",
            "mode": mode,
            "profile": PROFILE,
            "version": version,
            "release_checksums_sha256": release_identifier,
            "firmware_sha256": firmware_record["sha256"],
            "contains_sensitive_backup": mode == "migrate",
        }
        _write_journal(journal_path, journal)

    stage = journal["stage"]
    _stage_index(stage)
    backup = workspace / "device-backup"
    if _stage_index(stage) < _stage_index("backup_captured"):
        partial = workspace / "device-backup.partial"
        _replace_directory(partial, workspace)
        source_identity = None
        if mode == "migrate":
            transport.capture(BACKUP_PATHS, partial)
            source_identity = _validate_migration_source(partial)
        if backup.exists():
            _replace_directory(backup, workspace)
            backup.rmdir()
        os.replace(partial, backup)
        inventory = file_inventory(backup)
        journal.update({
            "stage": "backup_captured",
            "backup_files": len(inventory),
            "backup_identifier": inventory_identifier(inventory),
        })
        if source_identity is not None:
            journal["source"] = source_identity
        _write_journal(journal_path, journal)
        stage = journal["stage"]

    if _stage_index(stage) < _stage_index("backed_up"):
        inventory = file_inventory(backup)
        if inventory_identifier(inventory) != journal["backup_identifier"]:
            raise ValueError("device backup differs from the provisioning journal")
        if mode == "migrate":
            # Physical native-USB boards may expose the filesystem and the ROM
            # loader on different ports.  Persist the complete content-addressed
            # backup before immutable flash readback so --resume can continue
            # after an adult enters the ROM loader without recapturing state.
            transport.validate_source(mode, backup)
        journal["stage"] = "backed_up"
        _write_journal(journal_path, journal)
        stage = journal["stage"]

    if _stage_index(stage) < _stage_index("awaiting_health"):
        inventory = file_inventory(backup)
        if inventory_identifier(inventory) != journal["backup_identifier"]:
            raise ValueError("device backup differs from the provisioning journal")
        image = workspace / "prepared-image"
        prepare_image(
            release, backup, image, version=version, mode=mode,
            backup_identifier=journal["backup_identifier"])
        transport.install(
            firmware, firmware_record["flash_offset"], image,
            firmware_record["sha256"])
        journal["stage"] = "awaiting_health"
        journal["prepared_files"] = len(file_inventory(image))
        _write_journal(journal_path, journal)
        stage = journal["stage"]

    healthy = False
    if resume and stage == "awaiting_health":
        healthy = transport.release_is_healthy(version)
        if healthy:
            journal["stage"] = "complete"
            _write_journal(journal_path, journal)
            stage = "complete"
    return {
        "mode": mode,
        "profile": PROFILE,
        "version": version,
        "stage": stage,
        "healthy": healthy,
        "workspace": str(workspace),
        "sensitive_backup": mode == "migrate",
    }


class CommandTransport:
    """Physical USB transport using esptool 5 and MicroPython mpremote."""

    def __init__(self, port: str):
        if not port or any(character.isspace() for character in port):
            raise ValueError("a concrete serial port is required")
        self.port = port

    def _run(self, command: list[str], *, check: bool = True
             ) -> subprocess.CompletedProcess[str]:
        result = subprocess.run(
            command, check=False, text=True, stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT)
        if check and result.returncode:
            raise RuntimeError(
                "Command failed (%s):\n%s" % (
                    " ".join(command), result.stdout))
        return result

    def capture(self, paths: Sequence[str], destination: Path) -> None:
        """Capture protected files in one raw-REPL session without soft resets."""
        repl = RawRepl(self.port, timeout=20)
        try:
            repl.enter()
            files = [
                (remote, expected_size)
                for remote, expected_size in device_inventory(repl)
                if any(
                    remote == logical or remote.startswith(logical + "/")
                    for logical in paths)
            ]
            for remote, expected_size in files:
                target = (destination / remote.lstrip("/")).resolve()
                resolved_destination = destination.resolve()
                if resolved_destination != target and \
                        resolved_destination not in target.parents:
                    raise ValueError("unsafe remote backup path: " + remote)
                target.parent.mkdir(parents=True, exist_ok=True)
                code = (
                    "import ubinascii\n"
                    "f=open(%r,'rb')\n"
                    "while True:\n"
                    " d=f.read(384)\n"
                    " if not d: break\n"
                    " print(ubinascii.b2a_base64(d).decode().strip())\n"
                    "f.close()\n" % remote)
                encoded = repl.exec(
                    code, max(20, expected_size / 4000 + 10))
                content = b"".join(
                    base64.b64decode(line)
                    for line in encoded.splitlines() if line)
                if len(content) != expected_size:
                    raise IOError(
                        "size mismatch for %s: %d != %d" % (
                            remote, len(content), expected_size))
                target.write_bytes(content)
        finally:
            repl.close()

    def validate_source(self, mode: str, workspace: Path) -> None:
        if mode != "migrate":
            return
        self._check_tools()
        if sha256_file(LEGACY_FIRMWARE) != LEGACY_FIRMWARE_SHA256:
            raise ValueError("checked-in legacy firmware identity is invalid")
        readback = workspace / "legacy-firmware-readback.bin"
        try:
            self._run([
                "esptool", "--chip", "esp32s3", "--port", self.port,
                "read-flash", "0x0", str(LEGACY_FIRMWARE.stat().st_size),
                str(readback)])
            legacy_profile = _read_object(ROOT / "profiles/legacy-mp123.json")
            regions = legacy_profile["firmware_compatibility"].get(
                "runtime_identity_regions")
            if regions != LEGACY_IDENTITY_REGIONS:
                raise ValueError("legacy runtime identity region policy changed")
            with readback.open("rb") as stream:
                for region in regions:
                    stream.seek(region["offset"])
                    data = stream.read(region["size"])
                    if len(data) != region["size"] or \
                            hashlib.sha256(data).hexdigest() != region["sha256"]:
                        raise ValueError(
                            "connected device does not contain the supported "
                            "exact legacy-mp123 runtime")
        finally:
            if readback.is_file():
                readback.unlink()

    def _check_tools(self) -> None:
        if shutil.which("esptool") is None or shutil.which("mpremote") is None:
            raise RuntimeError("esptool and mpremote are required for --execute")
        version = self._run(["esptool", "version"]).stdout
        if not re.search(r"esptool v5\.", version):
            raise RuntimeError("TartLab provisioning requires esptool 5.x")
        self._run(["mpremote", "version"])

    def install(self, firmware: Path, offset: str, image: Path,
                expected_sha256: str) -> None:
        if sha256_file(firmware) != expected_sha256:
            raise ValueError("firmware changed after release verification")
        boot = image / "boot.py"
        main = image / "main.py"
        if not boot.is_file() or not main.is_file():
            raise ValueError("prepared image must contain boot.py and main.py")
        self._check_tools()
        verify = [
            "esptool", "--chip", "esp32s3", "--port", self.port,
            "verify-flash", offset, str(firmware)]
        # A failed filesystem upload can leave the exact firmware installed
        # while the journal remains at ``backed_up``.  Reuse that verified
        # image on resume instead of needlessly erasing and rewriting flash.
        firmware_matches = self._run(verify, check=False).returncode == 0
        if not firmware_matches:
            self._run(["esptool", "--chip", "esp32s3", "--port", self.port,
                       "erase-flash"])
            self._run(["esptool", "--chip", "esp32s3", "--port", self.port,
                       "--after", "hard-reset", "write-flash", offset,
                       str(firmware)])
            self._run(verify)
        # Native USB can remain in the ROM loader after verify-flash even when
        # a hard reset was requested.  The watchdog-reset exit is reliable on
        # the qualified ESP32-S3 board and does not alter flash.
        self._run([
            "esptool", "--chip", "esp32s3", "--port", self.port,
            "--after", "watchdog-reset", "chip-id"])
        placeholder = image.parent / "provisioning-placeholder.py"
        placeholder.write_text(
            "# TartLab provisioning transaction in progress.\n",
            encoding="utf-8", newline="\n")
        try:
            for destination in (":/boot.py", ":/main.py"):
                self._run([
                    "mpremote", "connect", self.port, "fs", "--force", "cp",
                    str(placeholder), destination])
            for source in sorted(image.iterdir(), key=lambda item: item.name):
                if source.name in ("boot.py", "main.py"):
                    continue
                destination = ":/" + source.name
                command = [
                    "mpremote", "connect", self.port, "fs", "--force"]
                if source.is_dir():
                    command.append("--recursive")
                    # mpremote's recursive copy treats an existing destination
                    # as the parent of the source directory.  Copy top-level
                    # directories into the existing root so flat directories
                    # are not misclassified as files.
                    destination = ":/"
                command.extend(("cp", str(source), destination))
                self._run(command)
            # Activate early boot only after recovery and state are complete;
            # keep main inert until the final copy.
            self._run([
                "mpremote", "connect", self.port, "fs", "--force", "cp",
                str(boot), ":/boot.py"])
            self._run([
                "mpremote", "connect", self.port, "fs", "--force", "cp",
                str(main), ":/main.py"])
        finally:
            if placeholder.is_file():
                placeholder.unlink()

    def release_is_healthy(self, version: str) -> bool:
        script = (
            "import ujson\n"
            "r={}\n"
            "try:\n"
            " r=ujson.load(open('/state/repos.json')); "
            "u=ujson.load(open('/state/update.json'))\n"
            "except OSError:\n u=None\n"
            "v=next((x.get('installed_version') for x in r.get('list', []) "
            "if x.get('name') == 'TartLab'), None)\n"
            "print('TARTLAB_HEALTH=' + ujson.dumps({'version':v,'update':u}))\n")
        boot = [
            "esptool", "--chip", "esp32s3", "--port", self.port,
            "--after", "watchdog-reset", "chip-id"]
        # The IDE event loop can make a late raw-REPL attach unreliable.  Boot
        # once and inspect state before the IDE owns the runtime, then clear the
        # diagnostic boot count and return the device to a normal boot.
        self._run(boot)
        # Windows exposes the native USB name before the endpoint is writable.
        # The qualified board needs a short fixed settle period; retries below
        # then cover any remaining enumeration variance.
        time.sleep(3)
        repl = None
        try:
            deadline = time.monotonic() + 10
            while repl is None:
                candidate = None
                try:
                    candidate = RawRepl(self.port, timeout=20)
                    candidate.enter()
                    repl = candidate
                except Exception:
                    if candidate is not None:
                        candidate.close()
                    if time.monotonic() >= deadline:
                        raise
                    time.sleep(0.2)
            output = repl.exec(script, 20).decode("utf-8", "replace")
            repl.exec(
                "import sys\n"
                "sys.path.insert(0,'/recovery')\n"
                "import recovery\n"
                "recovery._retry()\n", 20)
        finally:
            if repl is not None:
                repl.close()
            self._run(boot)
        match = re.search(r"TARTLAB_HEALTH=(\{.*\})", output)
        if not match:
            raise RuntimeError("device did not report TartLab health state")
        health = json.loads(match.group(1))
        return health.get("version") == version and health.get("update") is None


def _verify_attestations(release: Path, source_ref: str) -> None:
    qualification_bundle = release / "qualification-attestation.sigstore.json"
    release_bundle = release / "release-attestation.sigstore.json"
    present = [
        purpose for purpose, path in (
            ("qualification", qualification_bundle), ("release", release_bundle))
        if path.is_file()
    ]
    if len(present) != 1:
        raise ValueError(
            "modern provisioning requires exactly one qualification or release "
            "attestation bundle")
    subprocess.run([
        sys.executable, str(ROOT / "tools/check_modern_release_authenticity.py"),
        "--release", str(release), "--source-ref", source_ref,
        "--purpose", present[0], "--execute",
    ], cwd=ROOT, check=True)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--release", type=Path, required=True)
    parser.add_argument("--mode", choices=("clean", "migrate"), required=True)
    parser.add_argument("--workspace", type=Path)
    parser.add_argument("--port")
    parser.add_argument("--source-ref")
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--confirm-erase", action="store_true")
    parser.add_argument("--resume", action="store_true")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    manifest, release_identifier = _release_identity(args.release.resolve())
    if not args.execute:
        print(json.dumps({
            "mutation_performed": False,
            "mode": args.mode,
            "profile": PROFILE,
            "version": manifest["version"],
            "release_checksums_sha256": release_identifier,
            "next": (
                "rerun with --execute, --confirm-erase, --source-ref, --port, "
                "and a sensitive workspace outside the repository"),
        }, indent=2, sort_keys=True))
        return 0
    if not args.confirm_erase:
        raise ValueError("--execute requires --confirm-erase")
    if args.workspace is None or args.port is None or args.source_ref is None:
        raise ValueError(
            "--execute requires --workspace, --port, and --source-ref")
    expected_ref = "refs/tags/" + manifest["version"]
    if args.source_ref != expected_ref:
        raise ValueError("--source-ref must be %s" % expected_ref)
    _verify_attestations(args.release.resolve(), args.source_ref)
    result = provision(
        args.release, args.workspace, args.mode, CommandTransport(args.port),
        resume=args.resume)
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
