"""Declarative CrowPanel Basic 7-inch configuration; experimental, not qualified."""

BOARD_CONFIG = {
    "id": "elecrow_dis08070h",
    "pins": (
        {"type": "BACKLIGHT", "number": 2, "active_high": True},
        {"type": "DISPLAY_DATA_0", "number": 15},
        {"type": "DISPLAY_DATA_1", "number": 7},
        {"type": "DISPLAY_DATA_2", "number": 6},
        {"type": "DISPLAY_DATA_3", "number": 5},
        {"type": "DISPLAY_DATA_4", "number": 4},
        {"type": "DISPLAY_DATA_5", "number": 9},
        {"type": "DISPLAY_DATA_6", "number": 46},
        {"type": "DISPLAY_DATA_7", "number": 3},
        {"type": "DISPLAY_DATA_8", "number": 8},
        {"type": "DISPLAY_DATA_9", "number": 16},
        {"type": "DISPLAY_DATA_10", "number": 1},
        {"type": "DISPLAY_DATA_11", "number": 14},
        {"type": "DISPLAY_DATA_12", "number": 21},
        {"type": "DISPLAY_DATA_13", "number": 47},
        {"type": "DISPLAY_DATA_14", "number": 48},
        {"type": "DISPLAY_DATA_15", "number": 45},
        {"type": "DISPLAY_DE", "number": 41},
        {"type": "DISPLAY_VSYNC", "number": 40},
        {"type": "DISPLAY_HSYNC", "number": 39},
        {"type": "DISPLAY_PCLK", "number": 0},
        {"type": "TOUCH_SDA", "number": 19},
        {"type": "TOUCH_SCL", "number": 20},
        {"type": "SD_MOSI", "number": 11},
        {"type": "SD_MISO", "number": 13},
        {"type": "SD_SCK", "number": 12},
        {"type": "SD_CS", "number": 10},
    ),
    "display": {
        "driver": "rgb_display.RGBDisplay",
        "native_size": (800, 480),
        "logical_size": (800, 480),
        "rotation": 0,
        "transfer_rows": 24,
        "rgb": {
            "freq": 10_000_000,
            "hsync_front_porch": 40,
            "hsync_pulse_width": 48,
            "hsync_back_porch": 40,
            "vsync_front_porch": 1,
            "vsync_pulse_width": 31,
            "vsync_back_porch": 13,
            "hsync_idle_low": False,
            "vsync_idle_low": False,
            "de_idle_high": False,
            "pclk_idle_high": False,
            "pclk_active_low": True,
        },
    },
    "touch": {
        "driver": "gt911.GT911",
        "i2c": {"host": -1, "frequency": 10_000},
        "addresses": (0x5D, 0x14),
        "reset_expander": {
            "driver": "PCA9557", "address": 0x18,
            "reset_bit": 0, "interrupt_bit": 1,
            "assert_ms": 20, "release_ms": 100,
        },
    },
    "storage": {"interface": "spi", "host": 2, "frequency": 1_000_000},
}
